# CircleCi Config
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/wfinance

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      # Usa-se 'npm ci' para instalar as dependencias como se fosse um "NPM Install"
      - run: cd wfinance-ui && npm ci

      # Forçar um update do Web Drive
      - run: cd wfinance-ui && cd ./node_modules/protractor && npm i webdrivermanager@latest

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      # Roda os comandos do NPM
      - run: cd wfinance-ui && npm run style
      - run: cd wfinance-ui && npm run lint
      - run: cd wfinance-ui && npm run build:prod
      - run:
          name: Tar & Gzip compiled app
          command: cd wfinance-ui && tar zcf dist.tar.gz dist/wfinance-ui

      - store_artifacts:
          path: dist.tar.gz

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
