ALTER TABLE PESSOA ALTER COLUMN ESTADO DROP NOT NULL;
ALTER TABLE PESSOA ALTER COLUMN CEP DROP NOT NULL;
ALTER TABLE PESSOA ALTER COLUMN CIDADE DROP NOT NULL;
ALTER TABLE PESSOA ALTER COLUMN BAIRRO DROP NOT NULL;
ALTER TABLE PESSOA ALTER COLUMN LOGRADOURO DROP NOT NULL;
ALTER TABLE PESSOA ALTER COLUMN NUMERO DROP NOT NULL;
ALTER TABLE PESSOA ALTER COLUMN COMPLEMENTO DROP NOT NULL;
