INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Salário mensal', '2021-01-21', null, 6500.00, 'Distribuição de lucros', 'RECEITA', 1, 3);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Bahamas', '2021-01-21', '2017-02-10', 100.32, null, 'DESPESA', 2, 3);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Top Club', '2021-01-21', null, 120, null, 'RECEITA', 3, 3);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('CEMIG', '2021-01-21', '2017-02-10', 110.44, 'Geração', 'RECEITA', 3, 4);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('DMAE', '2021-01-21', null, 200.30, null, 'DESPESA', 3, 5);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Extra', '2021-01-10', '2017-03-10', 1010.32, null, 'RECEITA', 4, 3);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Bahamas', '2021-01-21', null, 500, null, 'RECEITA', 1, 7);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Top Club', '2021-03-10', '2017-03-10', 400.32, null, 'DESPESA', 4, 5);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Despachante', '2021-01-21', null, 123.64, 'Multas', 'DESPESA', 3, 9);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Pneus', '2021-04-10', '2017-04-10', 665.33, null, 'RECEITA', 5, 10);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Café', '2021-01-21', null, 8.32, null, 'DESPESA', 1, 5);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Eletrônicos', '2021-04-10', '2017-04-10', 2100.32, null, 'DESPESA', 5, 4);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Instrumentos', '2021-01-21', null, 1040.32, null, 'DESPESA', 4, 3);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Café', '2021-04-10', '2017-04-10', 4.32, null, 'DESPESA', 4, 4);
INSERT INTO LANCAMENTO (DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CATEGORIA_ID, PESSOA_ID)
VALUES ('Lanche', '2021-01-21', null, 10.20, null, 'DESPESA', 4, 4);
